@extends('coloquio.home')

@section('conteudo')
<h1>2018 – 11ª Edição internacional</h1>
<h2>Pontifícia Universidade Católica do Paraná-PUCPR</h2>
<h3>2 a 6 de setembro de 2018</h3>

<p align='justify'>O 14º Colóquio de Moda ocorreu na Pontifícia Universidade Católica do Paraná-PUCPR de 2 a 6 de setembro de 2018 em Curitiba. Reconhecida mundialmente por seu planejamento urbano e a preocupação com a inovação e a sustentabilidade, Curitiba também é uma das Smart Cities brasileiras, estacada pela revista Forbes como a terceira cidade mais sagaz do mundo, e pela UNESCO como uma das cidades criativas do Brasil, além de ser a capital brasileira com menor índice de analfabetismo.</p>
<p align='justify'>Assim como Curitiba a PUC Paraná se preocupa com a inovação nos processos de ensino e aprendizagem e uma das ações neste caminho foi receber o 14º Colóquio de Moda – 11ª Edição Internacional, 13º Fórum das Escolas de Moda e o 5º Congresso de Iniciação Cientifica em Design e Moda. Na organização do evento trabalharam, em parceira com a Abepem, docentes e discentes não apenas do curso de Design de Moda, mas também dos cursos de Design, Relações Públicas, Comunicação, Publicidade e Marketing em uma interdisciplinaridade que é tão comum para Moda.</p>
<p align='justify'>Em 4 dias de intensa atividades o evento buscou discutir o estado da arte da Moda e do Design, promover o intercâmbio e aproximação entre pesquisadores que atuem na área no Brasil e no exterior, contribuir para a consolidação acadêmica da Moda no Brasil. Além de divulgar a produção científica brasileira e internacional na área, assim recebidos 552 artigos dos quais 318 foram distribuídos em 15 Grupos de trabalhos (GT’s) e 234 nas Sessões de Iniciação Científica. Ampliando o intercâmbio acadêmico científico o evento contou com as palestras internacionais da professora Bárbara Guarducci da Kent State University campus Florença intitulada “New Paths for Creative Thinking” e da professora francesa Sophie Kurdajan com o tema “O Lançamento de Paris como Capital da Moda de 1868 a 1945. Além de conferências nacionais e mesas temáticas que versaram sobre Moda e Mercado, Tendências de Consumo, Moda e Memória, Moda e Ativismos, Moda e Tecnologia e Moda e Sustentabilidade. O evento recebeu também o 13º Fórum das Escolas de moda que discutiu sobre “Novas formas de pensar, agir, viver e ensinar”, o “Direito na Moda” e Comunicação Mídias e Tecnologia na Moda. Buscando fomentar a pesquisa que desperta no estudante o senso crítico para realidade em que vive, o 5º Congresso de Iniciação Científica em Design e Moda teve seu maior número de trabalhos aprovados até então, 158 artigos distribuídos em 8 Eixos temáticos. O evento contou ainda com 14 minicursos e oficinas.</p>
<p align='justify'>Consolidado como o maior espaço de intercâmbio acadêmico científico entre pesquisadores, docentes e estudantes o Colóquio estimula e valoriza a diversidade cultural e inter e transdisciplinaridade além da divulgação de novos conhecimentos por meio da pesquisa.</p>
@endsection
